### ISSUE TITLE
TRANSACTION_DIRECT_DEBIT webhook event uses positive number 

### ISSUE THREAD

**Issue by lwis** [starlingbank/api-samples#2]
When my application receives a `TRANSACTION_DIRECT_DEBIT` event it uses a positive number as the `amount`, while normal card transactions correctly use a negative number - is this intentional?

**Comment by domdomegg** [comment]
Hi Lewis - I believe this is the current behaviour. Work is being done to harmonise and improve some of the webhook models and this feedback will be taken onboard :)

Sorry for the delayed reply, for the fastest response to these kinds of questions you might want to check out our [Developer Slack](https://developer.starlingbank.com/community)
