### ISSUE TITLE
Vulnerability in example code

### ISSUE THREAD

**Issue by GrahamCampbell** [starlingbank/api-samples#5]
Your example code is vulnerable to timing attacks. An attacker can compute the signature needed to bypass the signing verification by a simple timing attack due to the code on line 17: https://github.com/starlingbank/api-samples/blob/master/webhook-verification/python/flask/app.py#L17.

**Comment by GrahamCampbell** [comment]
I mean, the example code also prints the secret 2 lines later, but it is obvious that someone using the example would change that, but not obvious to beginners (who would be exactly the sort of person to be using your examples), that line 17 is also bad, and needs changing.

**Comment by domdomegg** [comment]
Thank you for raising this, and sorry for the delay in addressing it. I've just merged a PR (#6) which should patch this vulnerability in the example webhook verification code for all languages.

**Comment by GrahamCampbell** [comment]
🍻
